// SPDX-FileCopyrightText: © 2024 Allegro DVT <github-ip@allegrodvt.com>
// SPDX-License-Identifier: MIT

#pragma once

/* Code generated DO NOT EDIT */

#include <stdint.h>
#include "msg_interface.h"

int enc_msg_interface_header_get_size(void);
void enc_msg_interface_header_marshall(struct msg_interface_header *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_header_unmarshall(struct msg_interface_header *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_cma_req_get_size(void);
void enc_msg_interface_get_cma_req_marshall(struct msg_interface_get_cma_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_cma_req_unmarshall(struct msg_interface_get_cma_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_cma_req_full_get_size(void);
void enc_msg_interface_get_cma_req_full_marshall(struct msg_interface_get_cma_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_cma_req_full_unmarshall(struct msg_interface_get_cma_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_cma_reply_get_size(void);
void enc_msg_interface_get_cma_reply_marshall(struct msg_interface_get_cma_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_cma_reply_unmarshall(struct msg_interface_get_cma_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_cma_reply_full_get_size(void);
void enc_msg_interface_get_cma_reply_full_marshall(struct msg_interface_get_cma_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_cma_reply_full_unmarshall(struct msg_interface_get_cma_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_put_cma_req_get_size(void);
void enc_msg_interface_put_cma_req_marshall(struct msg_interface_put_cma_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_put_cma_req_unmarshall(struct msg_interface_put_cma_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_put_cma_req_full_get_size(void);
void enc_msg_interface_put_cma_req_full_marshall(struct msg_interface_put_cma_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_put_cma_req_full_unmarshall(struct msg_interface_put_cma_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_put_cma_reply_get_size(void);
void enc_msg_interface_put_cma_reply_marshall(struct msg_interface_put_cma_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_put_cma_reply_unmarshall(struct msg_interface_put_cma_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_put_cma_reply_full_get_size(void);
void enc_msg_interface_put_cma_reply_full_marshall(struct msg_interface_put_cma_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_put_cma_reply_full_unmarshall(struct msg_interface_put_cma_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_perf_info_req_get_size(void);
void enc_msg_interface_perf_info_req_marshall(struct msg_interface_perf_info_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_perf_info_req_unmarshall(struct msg_interface_perf_info_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_perf_info_req_full_get_size(void);
void enc_msg_interface_perf_info_req_full_marshall(struct msg_interface_perf_info_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_perf_info_req_full_unmarshall(struct msg_interface_perf_info_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_perf_info_reply_get_size(void);
void enc_msg_interface_perf_info_reply_marshall(struct msg_interface_perf_info_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_perf_info_reply_unmarshall(struct msg_interface_perf_info_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_perf_info_reply_full_get_size(void);
void enc_msg_interface_perf_info_reply_full_marshall(struct msg_interface_perf_info_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_perf_info_reply_full_unmarshall(struct msg_interface_perf_info_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_write_req_get_size(void);
void enc_msg_interface_write_req_marshall(struct msg_interface_write_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_write_req_unmarshall(struct msg_interface_write_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_write_req_full_get_size(void);
void enc_msg_interface_write_req_full_marshall(struct msg_interface_write_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_write_req_full_unmarshall(struct msg_interface_write_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_AL_TStreamSectionInBuffer_get_size(void);
void enc_AL_TStreamSectionInBuffer_marshall(struct AL_TStreamSectionInBuffer *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_AL_TStreamSectionInBuffer_unmarshall(struct AL_TStreamSectionInBuffer *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_AL_TChunkInfo_get_size(void);
void enc_AL_TChunkInfo_marshall(struct AL_TChunkInfo *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_AL_TChunkInfo_unmarshall(struct AL_TChunkInfo *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_create_encoder_req_get_size(void);
void enc_msg_interface_create_encoder_req_marshall(struct msg_interface_create_encoder_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_create_encoder_req_unmarshall(struct msg_interface_create_encoder_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_create_encoder_req_full_get_size(void);
void enc_msg_interface_create_encoder_req_full_marshall(struct msg_interface_create_encoder_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_create_encoder_req_full_unmarshall(struct msg_interface_create_encoder_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_create_encoder_reply_get_size(void);
void enc_msg_interface_create_encoder_reply_marshall(struct msg_interface_create_encoder_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_create_encoder_reply_unmarshall(struct msg_interface_create_encoder_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_create_encoder_reply_full_get_size(void);
void enc_msg_interface_create_encoder_reply_full_marshall(struct msg_interface_create_encoder_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_create_encoder_reply_full_unmarshall(struct msg_interface_create_encoder_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_destroy_encoder_req_get_size(void);
void enc_msg_interface_destroy_encoder_req_marshall(struct msg_interface_destroy_encoder_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_destroy_encoder_req_unmarshall(struct msg_interface_destroy_encoder_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_destroy_encoder_req_full_get_size(void);
void enc_msg_interface_destroy_encoder_req_full_marshall(struct msg_interface_destroy_encoder_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_destroy_encoder_req_full_unmarshall(struct msg_interface_destroy_encoder_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_destroy_encoder_reply_get_size(void);
void enc_msg_interface_destroy_encoder_reply_marshall(struct msg_interface_destroy_encoder_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_destroy_encoder_reply_unmarshall(struct msg_interface_destroy_encoder_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_destroy_encoder_reply_full_get_size(void);
void enc_msg_interface_destroy_encoder_reply_full_marshall(struct msg_interface_destroy_encoder_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_destroy_encoder_reply_full_unmarshall(struct msg_interface_destroy_encoder_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_info_req_get_size(void);
void enc_msg_interface_get_info_req_marshall(struct msg_interface_get_info_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_info_req_unmarshall(struct msg_interface_get_info_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_info_req_full_get_size(void);
void enc_msg_interface_get_info_req_full_marshall(struct msg_interface_get_info_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_info_req_full_unmarshall(struct msg_interface_get_info_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_info_reply_get_size(void);
void enc_msg_interface_get_info_reply_marshall(struct msg_interface_get_info_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_info_reply_unmarshall(struct msg_interface_get_info_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_info_reply_full_get_size(void);
void enc_msg_interface_get_info_reply_full_marshall(struct msg_interface_get_info_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_info_reply_full_unmarshall(struct msg_interface_get_info_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_push_stream_buffer_req_get_size(void);
void enc_msg_interface_push_stream_buffer_req_marshall(struct msg_interface_push_stream_buffer_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_push_stream_buffer_req_unmarshall(struct msg_interface_push_stream_buffer_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_push_stream_buffer_req_full_get_size(void);
void enc_msg_interface_push_stream_buffer_req_full_marshall(struct msg_interface_push_stream_buffer_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_push_stream_buffer_req_full_unmarshall(struct msg_interface_push_stream_buffer_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_push_stream_buffer_reply_get_size(void);
void enc_msg_interface_push_stream_buffer_reply_marshall(struct msg_interface_push_stream_buffer_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_push_stream_buffer_reply_unmarshall(struct msg_interface_push_stream_buffer_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_push_stream_buffer_reply_full_get_size(void);
void enc_msg_interface_push_stream_buffer_reply_full_marshall(struct msg_interface_push_stream_buffer_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_push_stream_buffer_reply_full_unmarshall(struct msg_interface_push_stream_buffer_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_process_req_get_size(void);
void enc_msg_interface_process_req_marshall(struct msg_interface_process_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_process_req_unmarshall(struct msg_interface_process_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_process_req_full_get_size(void);
void enc_msg_interface_process_req_full_marshall(struct msg_interface_process_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_process_req_full_unmarshall(struct msg_interface_process_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_process_reply_get_size(void);
void enc_msg_interface_process_reply_marshall(struct msg_interface_process_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_process_reply_unmarshall(struct msg_interface_process_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_process_reply_full_get_size(void);
void enc_msg_interface_process_reply_full_marshall(struct msg_interface_process_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_process_reply_full_unmarshall(struct msg_interface_process_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_rec_req_get_size(void);
void enc_msg_interface_get_rec_req_marshall(struct msg_interface_get_rec_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_rec_req_unmarshall(struct msg_interface_get_rec_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_rec_req_full_get_size(void);
void enc_msg_interface_get_rec_req_full_marshall(struct msg_interface_get_rec_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_rec_req_full_unmarshall(struct msg_interface_get_rec_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_rec_reply_get_size(void);
void enc_msg_interface_get_rec_reply_marshall(struct msg_interface_get_rec_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_rec_reply_unmarshall(struct msg_interface_get_rec_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_rec_reply_full_get_size(void);
void enc_msg_interface_get_rec_reply_full_marshall(struct msg_interface_get_rec_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_rec_reply_full_unmarshall(struct msg_interface_get_rec_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_last_error_req_get_size(void);
void enc_msg_interface_get_last_error_req_marshall(struct msg_interface_get_last_error_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_last_error_req_unmarshall(struct msg_interface_get_last_error_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_last_error_req_full_get_size(void);
void enc_msg_interface_get_last_error_req_full_marshall(struct msg_interface_get_last_error_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_last_error_req_full_unmarshall(struct msg_interface_get_last_error_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_release_rec_req_get_size(void);
void enc_msg_interface_release_rec_req_marshall(struct msg_interface_release_rec_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_release_rec_req_unmarshall(struct msg_interface_release_rec_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_release_rec_req_full_get_size(void);
void enc_msg_interface_release_rec_req_full_marshall(struct msg_interface_release_rec_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_release_rec_req_full_unmarshall(struct msg_interface_release_rec_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_release_rec_reply_get_size(void);
void enc_msg_interface_release_rec_reply_marshall(struct msg_interface_release_rec_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_release_rec_reply_unmarshall(struct msg_interface_release_rec_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_release_rec_reply_full_get_size(void);
void enc_msg_interface_release_rec_reply_full_marshall(struct msg_interface_release_rec_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_release_rec_reply_full_unmarshall(struct msg_interface_release_rec_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_last_error_reply_get_size(void);
void enc_msg_interface_get_last_error_reply_marshall(struct msg_interface_get_last_error_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_last_error_reply_unmarshall(struct msg_interface_get_last_error_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_get_last_error_reply_full_get_size(void);
void enc_msg_interface_get_last_error_reply_full_marshall(struct msg_interface_get_last_error_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_get_last_error_reply_full_unmarshall(struct msg_interface_get_last_error_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_notify_req_get_size(void);
void enc_msg_interface_notify_req_marshall(struct msg_interface_notify_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_notify_req_unmarshall(struct msg_interface_notify_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_notify_req_full_get_size(void);
void enc_msg_interface_notify_req_full_marshall(struct msg_interface_notify_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_notify_req_full_unmarshall(struct msg_interface_notify_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_notify_reply_get_size(void);
void enc_msg_interface_notify_reply_marshall(struct msg_interface_notify_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_notify_reply_unmarshall(struct msg_interface_notify_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_notify_reply_full_get_size(void);
void enc_msg_interface_notify_reply_full_marshall(struct msg_interface_notify_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_notify_reply_full_unmarshall(struct msg_interface_notify_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_smart_req_get_size(void);
void enc_msg_interface_smart_req_marshall(struct msg_interface_smart_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_smart_req_unmarshall(struct msg_interface_smart_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_smart_req_full_get_size(void);
void enc_msg_interface_smart_req_full_marshall(struct msg_interface_smart_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_smart_req_full_unmarshall(struct msg_interface_smart_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_smart_reply_get_size(void);
void enc_msg_interface_smart_reply_marshall(struct msg_interface_smart_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_smart_reply_unmarshall(struct msg_interface_smart_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_smart_reply_full_get_size(void);
void enc_msg_interface_smart_reply_full_marshall(struct msg_interface_smart_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_smart_reply_full_unmarshall(struct msg_interface_smart_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_hdr_req_get_size(void);
void enc_msg_interface_hdr_req_marshall(struct msg_interface_hdr_req *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_hdr_req_unmarshall(struct msg_interface_hdr_req *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_hdr_req_full_get_size(void);
void enc_msg_interface_hdr_req_full_marshall(struct msg_interface_hdr_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_hdr_req_full_unmarshall(struct msg_interface_hdr_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_hdr_reply_get_size(void);
void enc_msg_interface_hdr_reply_marshall(struct msg_interface_hdr_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_hdr_reply_unmarshall(struct msg_interface_hdr_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_hdr_reply_full_get_size(void);
void enc_msg_interface_hdr_reply_full_marshall(struct msg_interface_hdr_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_hdr_reply_full_unmarshall(struct msg_interface_hdr_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_evt_buffer_refcount_get_size(void);
void enc_msg_interface_evt_buffer_refcount_marshall(struct msg_interface_evt_buffer_refcount *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_evt_buffer_refcount_unmarshall(struct msg_interface_evt_buffer_refcount *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_evt_buffer_refcount_full_get_size(void);
void enc_msg_interface_evt_buffer_refcount_full_marshall(struct msg_interface_evt_buffer_refcount_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_evt_buffer_refcount_full_unmarshall(struct msg_interface_evt_buffer_refcount_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_evt_end_encoding_get_size(void);
void enc_msg_interface_evt_end_encoding_marshall(struct msg_interface_evt_end_encoding *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_evt_end_encoding_unmarshall(struct msg_interface_evt_end_encoding *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_evt_end_encoding_full_get_size(void);
void enc_msg_interface_evt_end_encoding_full_marshall(struct msg_interface_evt_end_encoding_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_evt_end_encoding_full_unmarshall(struct msg_interface_evt_end_encoding_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_evt_end_encoding_with_stat_get_size(void);
void enc_msg_interface_evt_end_encoding_with_stat_marshall(struct msg_interface_evt_end_encoding_with_stat *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_evt_end_encoding_with_stat_unmarshall(struct msg_interface_evt_end_encoding_with_stat *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_evt_end_encoding_with_stat_full_get_size(void);
void enc_msg_interface_evt_end_encoding_with_stat_full_marshall(struct msg_interface_evt_end_encoding_with_stat_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_evt_end_encoding_with_stat_full_unmarshall(struct msg_interface_evt_end_encoding_with_stat_full *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_evt_destroy_marker_get_size(void);
void enc_msg_interface_evt_destroy_marker_marshall(struct msg_interface_evt_destroy_marker *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_evt_destroy_marker_unmarshall(struct msg_interface_evt_destroy_marker *out, void (*read_cb)(int, void *, void *), void *arg);
int enc_msg_interface_evt_destroy_marker_full_get_size(void);
void enc_msg_interface_evt_destroy_marker_full_marshall(struct msg_interface_evt_destroy_marker_full *in, void (*write_cb)(int, void *, void *), void *arg);
void enc_msg_interface_evt_destroy_marker_full_unmarshall(struct msg_interface_evt_destroy_marker_full *out, void (*read_cb)(int, void *, void *), void *arg);


