// SPDX-FileCopyrightText: © 2024 Allegro DVT <github-ip@allegrodvt.com>
// SPDX-License-Identifier: MIT

#pragma once

/* Code generated DO NOT EDIT */

#include <stdint.h>
#include "msg_itf.h"

int msg_itf_header_get_size(void);
void msg_itf_header_marshall(struct msg_itf_header *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_header_unmarshall(struct msg_itf_header *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_cma_req_get_size(void);
void msg_itf_get_cma_req_marshall(struct msg_itf_get_cma_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_cma_req_unmarshall(struct msg_itf_get_cma_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_cma_req_full_get_size(void);
void msg_itf_get_cma_req_full_marshall(struct msg_itf_get_cma_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_cma_req_full_unmarshall(struct msg_itf_get_cma_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_cma_reply_get_size(void);
void msg_itf_get_cma_reply_marshall(struct msg_itf_get_cma_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_cma_reply_unmarshall(struct msg_itf_get_cma_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_cma_reply_full_get_size(void);
void msg_itf_get_cma_reply_full_marshall(struct msg_itf_get_cma_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_cma_reply_full_unmarshall(struct msg_itf_get_cma_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_put_cma_req_get_size(void);
void msg_itf_put_cma_req_marshall(struct msg_itf_put_cma_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_put_cma_req_unmarshall(struct msg_itf_put_cma_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_put_cma_req_full_get_size(void);
void msg_itf_put_cma_req_full_marshall(struct msg_itf_put_cma_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_put_cma_req_full_unmarshall(struct msg_itf_put_cma_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_put_cma_reply_get_size(void);
void msg_itf_put_cma_reply_marshall(struct msg_itf_put_cma_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_put_cma_reply_unmarshall(struct msg_itf_put_cma_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_put_cma_reply_full_get_size(void);
void msg_itf_put_cma_reply_full_marshall(struct msg_itf_put_cma_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_put_cma_reply_full_unmarshall(struct msg_itf_put_cma_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_perf_info_req_get_size(void);
void msg_itf_perf_info_req_marshall(struct msg_itf_perf_info_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_perf_info_req_unmarshall(struct msg_itf_perf_info_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_perf_info_req_full_get_size(void);
void msg_itf_perf_info_req_full_marshall(struct msg_itf_perf_info_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_perf_info_req_full_unmarshall(struct msg_itf_perf_info_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_perf_info_reply_get_size(void);
void msg_itf_perf_info_reply_marshall(struct msg_itf_perf_info_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_perf_info_reply_unmarshall(struct msg_itf_perf_info_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_perf_info_reply_full_get_size(void);
void msg_itf_perf_info_reply_full_marshall(struct msg_itf_perf_info_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_perf_info_reply_full_unmarshall(struct msg_itf_perf_info_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_write_req_get_size(void);
void msg_itf_write_req_marshall(struct msg_itf_write_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_write_req_unmarshall(struct msg_itf_write_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_write_req_full_get_size(void);
void msg_itf_write_req_full_marshall(struct msg_itf_write_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_write_req_full_unmarshall(struct msg_itf_write_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int chunk_info_get_size(void);
void chunk_info_marshall(struct chunk_info *in, void (*write_cb)(int, void *, void *), void *arg);
void chunk_info_unmarshall(struct chunk_info *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_create_decoder_req_get_size(void);
void msg_itf_create_decoder_req_marshall(struct msg_itf_create_decoder_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_create_decoder_req_unmarshall(struct msg_itf_create_decoder_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_create_decoder_req_full_get_size(void);
void msg_itf_create_decoder_req_full_marshall(struct msg_itf_create_decoder_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_create_decoder_req_full_unmarshall(struct msg_itf_create_decoder_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_create_decoder_reply_get_size(void);
void msg_itf_create_decoder_reply_marshall(struct msg_itf_create_decoder_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_create_decoder_reply_unmarshall(struct msg_itf_create_decoder_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_create_decoder_reply_full_get_size(void);
void msg_itf_create_decoder_reply_full_marshall(struct msg_itf_create_decoder_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_create_decoder_reply_full_unmarshall(struct msg_itf_create_decoder_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_destroy_decoder_req_get_size(void);
void msg_itf_destroy_decoder_req_marshall(struct msg_itf_destroy_decoder_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_destroy_decoder_req_unmarshall(struct msg_itf_destroy_decoder_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_destroy_decoder_req_full_get_size(void);
void msg_itf_destroy_decoder_req_full_marshall(struct msg_itf_destroy_decoder_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_destroy_decoder_req_full_unmarshall(struct msg_itf_destroy_decoder_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_destroy_decoder_reply_get_size(void);
void msg_itf_destroy_decoder_reply_marshall(struct msg_itf_destroy_decoder_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_destroy_decoder_reply_unmarshall(struct msg_itf_destroy_decoder_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_destroy_decoder_reply_full_get_size(void);
void msg_itf_destroy_decoder_reply_full_marshall(struct msg_itf_destroy_decoder_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_destroy_decoder_reply_full_unmarshall(struct msg_itf_destroy_decoder_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_push_bitstream_buffer_req_get_size(void);
void msg_itf_push_bitstream_buffer_req_marshall(struct msg_itf_push_bitstream_buffer_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_push_bitstream_buffer_req_unmarshall(struct msg_itf_push_bitstream_buffer_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_push_bitstream_buffer_req_full_get_size(void);
void msg_itf_push_bitstream_buffer_req_full_marshall(struct msg_itf_push_bitstream_buffer_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_push_bitstream_buffer_req_full_unmarshall(struct msg_itf_push_bitstream_buffer_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_push_bitstream_buffer_reply_get_size(void);
void msg_itf_push_bitstream_buffer_reply_marshall(struct msg_itf_push_bitstream_buffer_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_push_bitstream_buffer_reply_unmarshall(struct msg_itf_push_bitstream_buffer_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_push_bitstream_buffer_reply_full_get_size(void);
void msg_itf_push_bitstream_buffer_reply_full_marshall(struct msg_itf_push_bitstream_buffer_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_push_bitstream_buffer_reply_full_unmarshall(struct msg_itf_push_bitstream_buffer_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_flush_req_get_size(void);
void msg_itf_flush_req_marshall(struct msg_itf_flush_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_flush_req_unmarshall(struct msg_itf_flush_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_flush_req_full_get_size(void);
void msg_itf_flush_req_full_marshall(struct msg_itf_flush_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_flush_req_full_unmarshall(struct msg_itf_flush_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_flush_reply_get_size(void);
void msg_itf_flush_reply_marshall(struct msg_itf_flush_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_flush_reply_unmarshall(struct msg_itf_flush_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_flush_reply_full_get_size(void);
void msg_itf_flush_reply_full_marshall(struct msg_itf_flush_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_flush_reply_full_unmarshall(struct msg_itf_flush_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_maxdepth_req_get_size(void);
void msg_itf_get_maxdepth_req_marshall(struct msg_itf_get_maxdepth_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_maxdepth_req_unmarshall(struct msg_itf_get_maxdepth_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_maxdepth_req_full_get_size(void);
void msg_itf_get_maxdepth_req_full_marshall(struct msg_itf_get_maxdepth_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_maxdepth_req_full_unmarshall(struct msg_itf_get_maxdepth_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_maxdepth_reply_get_size(void);
void msg_itf_get_maxdepth_reply_marshall(struct msg_itf_get_maxdepth_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_maxdepth_reply_unmarshall(struct msg_itf_get_maxdepth_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_maxdepth_reply_full_get_size(void);
void msg_itf_get_maxdepth_reply_full_marshall(struct msg_itf_get_maxdepth_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_maxdepth_reply_full_unmarshall(struct msg_itf_get_maxdepth_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_codec_req_get_size(void);
void msg_itf_get_codec_req_marshall(struct msg_itf_get_codec_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_codec_req_unmarshall(struct msg_itf_get_codec_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_codec_req_full_get_size(void);
void msg_itf_get_codec_req_full_marshall(struct msg_itf_get_codec_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_codec_req_full_unmarshall(struct msg_itf_get_codec_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_codec_reply_get_size(void);
void msg_itf_get_codec_reply_marshall(struct msg_itf_get_codec_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_codec_reply_unmarshall(struct msg_itf_get_codec_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_codec_reply_full_get_size(void);
void msg_itf_get_codec_reply_full_marshall(struct msg_itf_get_codec_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_codec_reply_full_unmarshall(struct msg_itf_get_codec_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_last_error_req_get_size(void);
void msg_itf_get_last_error_req_marshall(struct msg_itf_get_last_error_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_last_error_req_unmarshall(struct msg_itf_get_last_error_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_last_error_req_full_get_size(void);
void msg_itf_get_last_error_req_full_marshall(struct msg_itf_get_last_error_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_last_error_req_full_unmarshall(struct msg_itf_get_last_error_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_last_error_reply_get_size(void);
void msg_itf_get_last_error_reply_marshall(struct msg_itf_get_last_error_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_last_error_reply_unmarshall(struct msg_itf_get_last_error_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_get_last_error_reply_full_get_size(void);
void msg_itf_get_last_error_reply_full_marshall(struct msg_itf_get_last_error_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_get_last_error_reply_full_unmarshall(struct msg_itf_get_last_error_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_preallocate_buffers_req_get_size(void);
void msg_itf_preallocate_buffers_req_marshall(struct msg_itf_preallocate_buffers_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_preallocate_buffers_req_unmarshall(struct msg_itf_preallocate_buffers_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_preallocate_buffers_req_full_get_size(void);
void msg_itf_preallocate_buffers_req_full_marshall(struct msg_itf_preallocate_buffers_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_preallocate_buffers_req_full_unmarshall(struct msg_itf_preallocate_buffers_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_preallocate_buffers_reply_get_size(void);
void msg_itf_preallocate_buffers_reply_marshall(struct msg_itf_preallocate_buffers_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_preallocate_buffers_reply_unmarshall(struct msg_itf_preallocate_buffers_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_preallocate_buffers_reply_full_get_size(void);
void msg_itf_preallocate_buffers_reply_full_marshall(struct msg_itf_preallocate_buffers_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_preallocate_buffers_reply_full_unmarshall(struct msg_itf_preallocate_buffers_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_setparam_req_get_size(void);
void msg_itf_setparam_req_marshall(struct msg_itf_setparam_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_setparam_req_unmarshall(struct msg_itf_setparam_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_setparam_req_full_get_size(void);
void msg_itf_setparam_req_full_marshall(struct msg_itf_setparam_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_setparam_req_full_unmarshall(struct msg_itf_setparam_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_setparam_reply_get_size(void);
void msg_itf_setparam_reply_marshall(struct msg_itf_setparam_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_setparam_reply_unmarshall(struct msg_itf_setparam_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_setparam_reply_full_get_size(void);
void msg_itf_setparam_reply_full_marshall(struct msg_itf_setparam_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_setparam_reply_full_unmarshall(struct msg_itf_setparam_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_put_display_picture_req_get_size(void);
void msg_itf_put_display_picture_req_marshall(struct msg_itf_put_display_picture_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_put_display_picture_req_unmarshall(struct msg_itf_put_display_picture_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_put_display_picture_req_full_get_size(void);
void msg_itf_put_display_picture_req_full_marshall(struct msg_itf_put_display_picture_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_put_display_picture_req_full_unmarshall(struct msg_itf_put_display_picture_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_put_display_picture_reply_get_size(void);
void msg_itf_put_display_picture_reply_marshall(struct msg_itf_put_display_picture_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_put_display_picture_reply_unmarshall(struct msg_itf_put_display_picture_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_put_display_picture_reply_full_get_size(void);
void msg_itf_put_display_picture_reply_full_marshall(struct msg_itf_put_display_picture_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_put_display_picture_reply_full_unmarshall(struct msg_itf_put_display_picture_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_configure_output_settings_req_get_size(void);
void msg_itf_configure_output_settings_req_marshall(struct msg_itf_configure_output_settings_req *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_configure_output_settings_req_unmarshall(struct msg_itf_configure_output_settings_req *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_configure_output_settings_req_full_get_size(void);
void msg_itf_configure_output_settings_req_full_marshall(struct msg_itf_configure_output_settings_req_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_configure_output_settings_req_full_unmarshall(struct msg_itf_configure_output_settings_req_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_configure_output_settings_reply_get_size(void);
void msg_itf_configure_output_settings_reply_marshall(struct msg_itf_configure_output_settings_reply *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_configure_output_settings_reply_unmarshall(struct msg_itf_configure_output_settings_reply *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_configure_output_settings_reply_full_get_size(void);
void msg_itf_configure_output_settings_reply_full_marshall(struct msg_itf_configure_output_settings_reply_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_configure_output_settings_reply_full_unmarshall(struct msg_itf_configure_output_settings_reply_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_bitstream_buffer_refcount_get_size(void);
void msg_itf_evt_bitstream_buffer_refcount_marshall(struct msg_itf_evt_bitstream_buffer_refcount *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_bitstream_buffer_refcount_unmarshall(struct msg_itf_evt_bitstream_buffer_refcount *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_bitstream_buffer_refcount_full_get_size(void);
void msg_itf_evt_bitstream_buffer_refcount_full_marshall(struct msg_itf_evt_bitstream_buffer_refcount_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_bitstream_buffer_refcount_full_unmarshall(struct msg_itf_evt_bitstream_buffer_refcount_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_display_picture_refcount_get_size(void);
void msg_itf_evt_display_picture_refcount_marshall(struct msg_itf_evt_display_picture_refcount *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_display_picture_refcount_unmarshall(struct msg_itf_evt_display_picture_refcount *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_display_picture_refcount_full_get_size(void);
void msg_itf_evt_display_picture_refcount_full_marshall(struct msg_itf_evt_display_picture_refcount_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_display_picture_refcount_full_unmarshall(struct msg_itf_evt_display_picture_refcount_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_resolution_found_get_size(void);
void msg_itf_evt_resolution_found_marshall(struct msg_itf_evt_resolution_found *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_resolution_found_unmarshall(struct msg_itf_evt_resolution_found *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_resolution_found_full_get_size(void);
void msg_itf_evt_resolution_found_full_marshall(struct msg_itf_evt_resolution_found_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_resolution_found_full_unmarshall(struct msg_itf_evt_resolution_found_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_end_parsing_get_size(void);
void msg_itf_evt_end_parsing_marshall(struct msg_itf_evt_end_parsing *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_end_parsing_unmarshall(struct msg_itf_evt_end_parsing *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_end_parsing_full_get_size(void);
void msg_itf_evt_end_parsing_full_marshall(struct msg_itf_evt_end_parsing_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_end_parsing_full_unmarshall(struct msg_itf_evt_end_parsing_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_end_decoding_get_size(void);
void msg_itf_evt_end_decoding_marshall(struct msg_itf_evt_end_decoding *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_end_decoding_unmarshall(struct msg_itf_evt_end_decoding *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_end_decoding_full_get_size(void);
void msg_itf_evt_end_decoding_full_marshall(struct msg_itf_evt_end_decoding_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_end_decoding_full_unmarshall(struct msg_itf_evt_end_decoding_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_display_get_size(void);
void msg_itf_evt_display_marshall(struct msg_itf_evt_display *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_display_unmarshall(struct msg_itf_evt_display *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_display_full_get_size(void);
void msg_itf_evt_display_full_marshall(struct msg_itf_evt_display_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_display_full_unmarshall(struct msg_itf_evt_display_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_display_with_hdr_get_size(void);
void msg_itf_evt_display_with_hdr_marshall(struct msg_itf_evt_display_with_hdr *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_display_with_hdr_unmarshall(struct msg_itf_evt_display_with_hdr *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_display_with_hdr_full_get_size(void);
void msg_itf_evt_display_with_hdr_full_marshall(struct msg_itf_evt_display_with_hdr_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_display_with_hdr_full_unmarshall(struct msg_itf_evt_display_with_hdr_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_sei_buf_get_size(void);
void msg_itf_evt_sei_buf_marshall(struct msg_itf_evt_sei_buf *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_sei_buf_unmarshall(struct msg_itf_evt_sei_buf *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_sei_buf_full_get_size(void);
void msg_itf_evt_sei_buf_full_marshall(struct msg_itf_evt_sei_buf_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_sei_buf_full_unmarshall(struct msg_itf_evt_sei_buf_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_sei_msg_get_size(void);
void msg_itf_evt_sei_msg_marshall(struct msg_itf_evt_sei_msg *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_sei_msg_unmarshall(struct msg_itf_evt_sei_msg *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_sei_msg_full_get_size(void);
void msg_itf_evt_sei_msg_full_marshall(struct msg_itf_evt_sei_msg_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_sei_msg_full_unmarshall(struct msg_itf_evt_sei_msg_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_error_get_size(void);
void msg_itf_evt_error_marshall(struct msg_itf_evt_error *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_error_unmarshall(struct msg_itf_evt_error *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_error_full_get_size(void);
void msg_itf_evt_error_full_marshall(struct msg_itf_evt_error_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_error_full_unmarshall(struct msg_itf_evt_error_full *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_destroy_marker_get_size(void);
void msg_itf_evt_destroy_marker_marshall(struct msg_itf_evt_destroy_marker *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_destroy_marker_unmarshall(struct msg_itf_evt_destroy_marker *out, void (*read_cb)(int, void *, void *), void *arg);
int msg_itf_evt_destroy_marker_full_get_size(void);
void msg_itf_evt_destroy_marker_full_marshall(struct msg_itf_evt_destroy_marker_full *in, void (*write_cb)(int, void *, void *), void *arg);
void msg_itf_evt_destroy_marker_full_unmarshall(struct msg_itf_evt_destroy_marker_full *out, void (*read_cb)(int, void *, void *), void *arg);


